apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/base/logging
patches:
  - target:
      kind: Deployment
      name: logging
    patch: |-
      - op: add
        path: /metadata/labels/location
        value: us-east
      - op: add
        path: /spec/template/metadata/labels/location
        value: us-east
